export let dummyData = [
  {
    name: "Denver's Best Tournament",
    schedule: "First Friday of each month",
    startTime: "5:00 PM",
    endTime: "10:00 PM",
    venueFee: "$10 ($5 venue fee and $5 pot bonus)",
    setupBonus: "Free entry if you bring a full setup with DLC unlocked",
    hasMelee: false,
    hasN64: false,
    bannedCharacters: "None",
    over18: true,
    over21: false,
    preReg: "Optional",
    preRegLink: "https://www.coloradossbu.com"
  },
  {
    name: "Boulder's Best Tournament",
    schedule: "Second and fourth Saturday of each month",
    startTime: "3:00 PM",
    endTime: "8:00 PM",
    venueFee: "$15 ($5 venue fee and $10 pot bonus)",
    setupBonus: "$5 for entry if you bring a full setup with DLC unlocked",
    hasMelee: true,
    hasN64: true,
    bannedCharacters: "Steve",
    over18: false,
    over21: false,
    preReg: "Optional",
    preRegLink: "https://www.coloradossbu.com"
  },
  {
    name: "Ft. Collins Crashers",
    schedule: "Wednesday, every week",
    startTime: "6:00 PM",
    endTime: "9:30 PM",
    venueFee: "$10 ($5 venue fee and $5 pot bonus)",
    setupBonus: "Free entry if you bring a full setup with DLC unlocked",
    hasMelee: true,
    hasN64: false,
    bannedCharacters: "None",
    over18: false,
    over21: false,
    preReg: false,
    preRegLink: false
  },
  {
    name: "Smash in the Springs",
    schedule: "Sunday, every week",
    startTime: "5:00 PM",
    endTime: "10:00 PM",
    venueFee: "$10 ($5 venue fee and $5 pot bonus)",
    setupBonus: "Free entry if you bring a full setup with DLC unlocked",
    hasMelee: false,
    hasN64: false,
    bannedCharacters: "None",
    over18: false,
    over21: true,
    preReg: false,
    preRegLink: null,
  },
  {
    name: "BRING THE PAIN 7",
    schedule: "Saturday, 02/26/22",
    startTime: "9:00 AM",
    endTime: "9:00 PM",
    venueFee: "$20 ($10 venue fee and $10 pot bonus)",
    setupBonus: "$10 entry fee if you bring a full setup with DLC unlocked",
    hasMelee: true,
    hasN64: true,
    bannedCharacters: "None",
    over18: false,
    over21: false,
    preReg: "Required",
    preRegLink: "https://www.coloradossbu.com"
  }
];
